[package]
name = "wasm-rpc-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "wasm_rpc_client"
path = "src/lib.rs"

[dependencies]
flatbuffers-schemas-rust = { path = "../flatbuffers-schemas-rust" }
